name: CsGoPlugin
main: com.cospox.csgoplugin.Main
version: 0.0.1
api-version: 1.17
commands:
    jointeam:
        description: Join a team
        usage: /jointeam <team> (one of ct or t)
        permission: csgo.jointeam
    startgame:
        description: Start the game
        usage: /startgame
        permission: csgo.startgame

